config/routes.rb
Rails.application.routes.draw do
  resources :movies
  root to: 'movies#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/movie.rb
class Movie < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :set_locale

  def set_locale
    session[:locale] = params[:locale] if params[:locale].present?
    I18n.locale = session[:locale] || I18n.default_locale
  end
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  before_action :set_movie, only: [:show, :edit, :update, :destroy]

  # GET /movies
  # GET /movies.json
  def index
    @movies = Movie.all
  end

  # GET /movies/1
  # GET /movies/1.json
  def show
  end

  # GET /movies/new
  def new
    @movie = Movie.new
  end

  # GET /movies/1/edit
  def edit
  end

  # POST /movies
  # POST /movies.json
  def create
    @movie = Movie.new(movie_params)

    respond_to do |format|
      if @movie.save
        format.html { redirect_to @movie, notice: 'Movie was successfully created.' }
        format.json { render :show, status: :created, location: @movie }
      else
        format.html { render :new }
        format.json { render json: @movie.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /movies/1
  # PATCH/PUT /movies/1.json
  def update
    respond_to do |format|
      if @movie.update(movie_params)
        format.html { redirect_to @movie, notice: 'Movie was successfully updated.' }
        format.json { render :show, status: :ok, location: @movie }
      else
        format.html { render :edit }
        format.json { render json: @movie.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /movies/1
  # DELETE /movies/1.json
  def destroy
    @movie.destroy
    respond_to do |format|
      format.html { redirect_to movies_url, notice: 'Movie was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_movie
      @movie = Movie.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def movie_params
      params.require(:movie).permit(:name, :director, :run_time, :release_date)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>OneBitCine</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <div class="container">
      <a href="<%= request.path %>?locale=en">
        <span class="flag-icon flag-icon-us"></span>
      </a>
      <a href="<%= request.path %>?locale=pt-BR">
        <span class="flag-icon flag-icon-br"></span>
      </a>
      <%= yield %>
    </div>
  </body>
</html>

app/views/movies/_form.html.erb
<%= form_with(model: movie, local: true) do |form| %>
 <% if movie.errors.any? %>
   <div id="error_explanation">
     <h2><%= pluralize(movie.errors.count, "error") %> prohibited this movie from being saved:</h2>

     <ul>
     <% movie.errors.full_messages.each do |message| %>
       <li><%= message %></li>
     <% end %>
     </ul>
   </div>
 <% end %>

 <div class="field">
   <%= form.label :name %>
   <%= form.text_field :name %>
 </div>

 <div class="field">
   <%= form.label :director %>
   <%= form.text_field :director %>
 </div>

 <div class="field">
   <%= form.label :run_time %>
   <%= form.text_field :run_time %>
 </div>

 <div class="field">
   <%= form.label :release_date %>
   <%= form.date_field :release_date %>
 </div>

 <div class="btn waves-effect waves-light">
   <%= form.submit %>
 </div>
<% end %>

app/views/movies/edit.html.erb
<h1><%= translate 'actions.edit'%> <%= @movie.model_name.human %> </h1>

<%= render 'form', movie: @movie %>

<%= link_to "#{translate 'actions.show'}", @movie %>
<%= link_to "#{translate 'actions.back'}", movies_path %>

app/views/movies/index.html.erb
<p id="notice"><%= notice %></p>

<h1><%= translate 'movies.title' %></h1>
<h4><%= translate 'movies.subtitle' %></h4>

<table>
  <thead>
    <tr>
      <th><%= @movies.human_attribute_name("name") %></th>
      <th><%= @movies.human_attribute_name("director") %></th>
      <th><%= @movies.human_attribute_name("run_time") %></th>
      <th><%= @movies.human_attribute_name("release_date") %></th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @movies.each do |movie| %>
      <tr>
        <td><%= movie.name %></td>
        <td><%= movie.director %></td>
        <td><%= movie.run_time %></td>
        <td><%= localize(movie.release_date, format: :long) %></td>
        <td><%= link_to "#{translate 'actions.show'}", movie %></td>
        <td><%= link_to "#{translate 'actions.edit'}", edit_movie_path(movie) %></td>
        <td><%= link_to "#{translate 'actions.destroy'}", movie, method: :delete, data: { confirm: "#{translate 'confirm'}" } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to "#{translate 'actions.new'}", new_movie_path %>

app/views/movies/new.html.erb
<h1><%= translate 'actions.new'%> <%= @movie.model_name.human %> </h1>

<%= render 'form', movie: @movie %>

<%= link_to "#{translate 'actions.back'}", movies_path %>

app/views/movies/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong><%= translate 'activerecord.attributes.movie.name'%>:</strong>
  <%= @movie.name %>
</p>

<p>
  <strong><%= translate 'activerecord.attributes.movie.director'%>:</strong>
  <%= @movie.director %>
</p>

<p>
  <strong><%= translate 'activerecord.attributes.movie.run_time'%>:</strong>
  <%= @movie.run_time %>
</p>

<p>
  <strong><%= translate 'activerecord.attributes.movie.release_date'%>:</strong>
  <%= localize(@movie.release_date, format: :long) %>
</p>

<%= link_to "#{translate 'actions.edit'}", edit_movie_path(@movie) %> |
<%= link_to "#{translate 'actions.back'}", movies_path %>